### ISSUE TITLE
AMD would like to submit pull request for a (new) hip branch.

### ISSUE THREAD

**Issue by rwvo** [lanl/PENNANT#5]
We have been working at a hip branch at AMD to make PENNANT run on AMD GPU hardware. We would like to submit a pull request for a new hip branch, but as far as I know, it isn't possible to create a new branch in a parent repository in a pull request.

Could you please create a **hip** branch based off the head of the **cuda** branch (commit 6c4e0d15a802349c454eeb772d9817630c47d175), so that I can submit a pull request with our modifications and additions?

**Comment by jpietarilagraham** [comment]
Done:
https://github.com/lanl/PENNANT/tree/hip

**Comment by rwvo** [comment]
Thanks, pull request submitted
